FROM modbus

# Import environment variable to pass as parameter to make (e.g., to make parallel builds with -j)
ARG MAKE_OPT

# Set up StateAFL
ENV STATEAFL="/home/ubuntu/stateafl"
ENV STATEAFL_CFLAGS="-DBLACKLIST_ALLOC_SITES"

RUN git clone https://github.com/stateafl/stateafl.git $STATEAFL && \
    cd $STATEAFL && \
    make clean all $MAKE_OPT && \
    rm as && \
    cd llvm_mode && CFLAGS="${STATEAFL_CFLAGS}" make $MAKE_OPT

# Set up environment variables for StateAFL
ENV AFL_PATH=${STATEAFL}
ENV PATH=${STATEAFL}:${PATH}

COPY --chown=ubuntu:ubuntu stateafl.patch ${WORKDIR}/mbus-stateafl.patch

RUN cd $WORKDIR && rm -rf m-bus && git clone --recurse-submodules https://github.com/rtlabs-com/m-bus.git && \
    cd m-bus && patch -p1 < $WORKDIR/mbus-stateafl.patch && \
    cmake -B build && \
    cmake --build build --target all check